-- DROP TABLE FILES CASCADE CONSTRAINTS
/
CREATE TABLE FILES
(
   FILE_ID			VARCHAR2 (20),
   FILE_NAME		VARCHAR2 (300),
   FILE_PATH			VARCHAR2 (300),
   FILE_SIZE			LONG,
   CONTENT_TYPE	VARCHAR2 (20)
 )
/