-- DROP TABLE MEMBER CASCADE CONSTRAINTS
/
CREATE TABLE MEMBER
(
   MEMBER_ID      INT NOT NULL,
   MEMBER_NAME    VARCHAR2 (100) NOT NULL,
   MEMBER_EMAIL   VARCHAR2 (200) NOT NULL,
   MEMBER_PW      VARCHAR2 (200) NOT NULL,
   PRIMARY KEY (MEMBER_ID),
   CONSTRAINT U_MEMBER_EMAIL UNIQUE (MEMBER_EMAIL)
   )
/

-- DROP SEQUENCE SEQ_MEMBER
/
CREATE SEQUENCE SEQ_MEMBER
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
CACHE 10
/